# Generated by Django 4.2 on 2024-04-20 18:17

import cis.models.crontab
import cis.storage_backend
import cis.utils
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True)),
                ('salutation', models.CharField(blank=True, max_length=500, null=True)),
                ('ssn', models.CharField(blank=True, max_length=15, null=True)),
                ('psid', models.CharField(blank=True, max_length=10, null=True)),
                ('alt_email', models.EmailField(blank=True, max_length=254)),
                ('secondary_email', models.EmailField(blank=True, max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address1', models.CharField(blank=True, max_length=500)),
                ('address2', models.CharField(blank=True, max_length=500)),
                ('po_box', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=100)),
                ('primary_phone', models.CharField(blank=True, max_length=50)),
                ('secondary_phone', models.CharField(blank=True, max_length=50)),
                ('alt_phone', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country_of_birth', models.CharField(blank=True, max_length=3, null=True)),
                ('account_enabled', models.BooleanField(default=False)),
                ('require_password_reset', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('campus', models.JSONField(blank=True, null=True)),
                ('education_background', models.JSONField(blank=True, null=True)),
                ('previous_names', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['last_name'],
                'permissions': [('create_user', 'Can create new user')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cost_per_credit', models.FloatField(default=0.0)),
                ('hs_start_date', models.DateField(blank=True, null=True)),
                ('hs_end_date', models.DateField(blank=True, null=True)),
                ('temp_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantCourseReviewer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('---', '---'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Need more information', 'Need more information')], default='---', max_length=50)),
                ('misc_info', models.JSONField(blank=True, null=True)),
                ('status_changed_on', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_on', models.DateField(auto_now=True)),
                ('recommendation', models.JSONField(blank=True, null=True)),
                ('submitter', models.JSONField(blank=True, null=True)),
                ('upload', models.FileField(storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.utils.recommendation_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantSchoolCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('misc_info', models.JSONField()),
                ('status', models.CharField(choices=[('---', '---'), ('Accepted', 'Accepted'), ('Conditionally Accepted', 'Conditionally Accepted'), ('Denied', 'Denied')], default='---', max_length=50)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('associated_with', models.JSONField(blank=True, null=True)),
                ('upload', models.FileField(blank=True, storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.utils.teacher_app_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('code', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('temp_id', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_number', models.IntegerField()),
                ('section_number', models.CharField(max_length=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('highschool_course_name', models.CharField(blank=True, max_length=500)),
                ('credit_hours', models.FloatField(default=1)),
                ('days', models.CharField(blank=True, max_length=50)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('instruction_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('prereq', models.TextField(blank=True)),
                ('max_enrollment', models.IntegerField(default=0)),
                ('min_enrollment', models.IntegerField(default=0)),
                ('lab_fees', models.FloatField(default=0)),
                ('enrollment', models.IntegerField(default=0)),
                ('available_seats', models.IntegerField(default=0)),
                ('last_imported_on', models.DateField(auto_now=True)),
                ('room_alias', models.CharField(blank=True, max_length=10, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('notifications', models.JSONField(blank=True, null=True)),
                ('period_time', models.CharField(blank=True, max_length=500, null=True)),
                ('free_period', models.CharField(blank=True, max_length=500, null=True)),
                ('roster_status', models.CharField(blank=True, choices=[('', ''), ('pending verification', 'Pending Verification'), ('accurate', 'Accurate'), ('inaccurate', 'Inaccurate')], default='', max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=30, null=True)),
                ('roster_status_changed_on', models.JSONField(blank=True, null=True)),
                ('syllabi_status', models.CharField(blank=True, choices=[('', ''), ('pending review', 'Pending Review'), ('reviewed', 'Reviewed'), ('needs update', 'Needs Update')], default='', max_length=30, null=True)),
                ('syllabi_status_changed_on', models.JSONField(default=dict)),
                ('grade_status', models.CharField(blank=True, choices=[('', 'N/A'), ('saved', 'Grades Saved Only'), ('submitted', 'Grades Successfully Submitted')], default='', max_length=30, null=True)),
                ('grade_status_changed_on', models.JSONField(blank=True, null=True)),
                ('part_of_term', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSectionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('parent', models.UUIDField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['createdon'],
            },
        ),
        migrations.CreateModel(
            name='ClassSectionSyllabi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('media', models.FileField(storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.utils.syllabus_upload_path)),
                ('status', models.CharField(choices=[('---', '---'), ('pending review', 'Pending Review'), ('Reviewed', 'Reviewed')], default='pending review', max_length=20)),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassVisitReportNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('parent', models.UUIDField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['createdon'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('designator', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('', '---'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('temp_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CohortAffiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('since', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CohortParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('avb_position', models.CharField(blank=True, max_length=50, null=True)),
                ('avb_location', models.CharField(blank=True, max_length=50, null=True)),
                ('avb_affiliation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('temp_id', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('catalog_number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_hours', models.FloatField(default=1)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('teacher_requirement', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prereq', models.TextField(blank=True, null=True, verbose_name='Pre-reqs')),
                ('stream', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Humanities', 'Humanities & Social Sciences'), ('Languages', 'Languages'), ('STEM', 'STEM'), ('Business & Tech.', 'Business & Tech.')], max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('temp_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['cohort__designator', 'catalog_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseAdministrator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Faculty', 'Faculty'), ('Visitor', 'Visitor'), ('Dept. Chair', 'Dept. Chair'), ('Dean', 'Dean')], default='Administrator', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAppRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('required', models.CharField(choices=[('', 'Select'), ('1', 'Yes'), ('2', 'No')], default=1, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CourseNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('parent', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['createdon'],
            },
        ),
        migrations.CreateModel(
            name='CourseUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('Syllabus', 'Syllabus'), ('Syllabus Template', 'Syllabus Template'), ('Course Resource', 'Course Resource')], default='Transcript', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('media', models.FileField(storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.utils.course_files_upload_path)),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CronLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_completed_on', models.DateTimeField(blank=True, null=True)),
                ('run_started_on', models.DateTimeField(blank=True, null=True)),
                ('run_scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('log_file', models.FileField(blank=True, storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.models.crontab.cron_log_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='CronTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron', models.CharField(max_length=20)),
                ('command', models.CharField(max_length=100, unique=True)),
                ('last_run_completed_on', models.DateTimeField(blank=True, null=True)),
                ('last_run_started_on', models.DateTimeField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('temp_id', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('address1', models.CharField(blank=True, max_length=500)),
                ('address2', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=100)),
                ('primary_phone', models.CharField(blank=True, max_length=50)),
                ('temp_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DistrictAdministrator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictAdministratorPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Retired', 'Retired')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('type', models.CharField(choices=[('Type 1', 'Type 1`'), ('Type 2', 'Type 2'), ('Type 3', 'Type 3')], default='Type 1', max_length=30)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('---', '---'), ('Invited', 'Invited'), ('Confirmed', 'Confirmed'), ('Attended', 'Attended'), ('Not Attended', 'Not Attended')], default='---', max_length=30)),
                ('participation', models.CharField(choices=[('Optional', 'Optional'), ('Required', 'Required')], default='Optional', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventCohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.JSONField()),
                ('item_type', models.CharField(choices=[('speaker', 'Speaker'), ('refreshment', 'Refreshment'), ('copies', 'Copies'), ('cis expense', 'CIS Expense'), ('cohort expense', 'Cohort Expense')], default='speaker', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCoordinator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('fac_assistant', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_id', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FutureCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_on', models.DateField(auto_now=True)),
                ('last_viewed_on', models.DateField(auto_now_add=True)),
                ('submitted_on', models.DateField(blank=True, null=True)),
                ('section_info', models.JSONField(default=dict)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(default='-', max_length=10)),
                ('sau', models.CharField(default='-', max_length=100)),
                ('address1', models.CharField(blank=True, max_length=500)),
                ('address2', models.CharField(blank=True, max_length=500)),
                ('po_box', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=100)),
                ('primary_phone', models.CharField(blank=True, max_length=50)),
                ('secondary_phone', models.CharField(blank=True, max_length=50)),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('temp_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('', '---'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30)),
                ('state_code', models.CharField(blank=True, max_length=10)),
                ('hs_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('-', '-')], max_length=15)),
                ('oncampus_sections', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HSAdministrator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SIS_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('message_type', models.CharField(choices=[('person_create', 'Person Create'), ('class_registered', 'Register'), ('class_dropped', 'Drop'), ('class_list', 'Class List')], max_length=50)),
                ('message', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SIS_Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('message', models.JSONField(blank=True, default=dict)),
                ('processed_message', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('account_verified', models.BooleanField(default=False)),
                ('account_verified_on', models.DateTimeField(blank=True, null=True)),
                ('sis_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('sis_sent_on', models.DateTimeField(blank=True, null=True)),
                ('sis_applied_on', models.DateTimeField(blank=True, null=True)),
                ('sis_admitted_on', models.DateTimeField(blank=True, null=True)),
                ('sis_matriculated_on', models.DateTimeField(blank=True, null=True)),
                ('sis_status', models.CharField(choices=[('pending', 'Pending'), ('request_sent', 'Request Sent'), ('admitted', 'Admitted, waiting Matriculation'), ('matriculated', 'Matriculated')], default='pending', max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('preferred_name', models.CharField(blank=True, max_length=50, null=True)),
                ('pidm', models.CharField(blank=True, max_length=50)),
                ('tuition_owed', models.FloatField(blank=True, null=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('graduation_year', models.SmallIntegerField(blank=True, null=True)),
                ('parent_first_name', models.CharField(blank=True, max_length=50)),
                ('parent_last_name', models.CharField(blank=True, max_length=50)),
                ('parent_email', models.CharField(blank=True, max_length=50)),
                ('state_id', models.CharField(blank=True, max_length=50, null=True)),
                ('parent1_education_level', models.CharField(blank=True, choices=[('', 'Select'), ('1', 'Less than a high school diploma'), ('2', 'High school diploma'), ('3', 'Some college but no degree'), ('4', "Associate's degree (2 years)"), ('5', "Bachelor's degree (4 years)"), ('6', "Master's Degree or higher"), ('7', "I don't know")], max_length=2)),
                ('parent2_education_level', models.CharField(blank=True, choices=[('', 'Select'), ('1', 'Less than a high school diploma'), ('2', 'High school diploma'), ('3', 'Some college but no degree'), ('4', "Associate's degree (2 years)"), ('5', "Bachelor's degree (4 years)"), ('6', "Master's Degree or higher"), ('7', "I don't know")], max_length=2)),
                ('gender', models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('non-binary', 'non-binary')], max_length=10)),
                ('hispanic', models.CharField(blank=True, choices=[('', 'Select'), (True, 'Yes'), (False, 'No')], max_length=10, null=True)),
                ('ethnicity', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'American Indian/Alaska Native'), (2, 'Asian'), (3, 'Black/African American'), (4, 'Native Hawaiian/Other Pacific Islander'), (5, 'White')], max_length=10)),
                ('gender_identity', models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('non-binary', 'non-binary')], default='', max_length=10, null=True)),
                ('gender_pronoun', models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('non-binary', 'non-binary')], default='', max_length=10, null=True)),
                ('hispanic_background', models.CharField(blank=True, choices=[(1, 'Central American'), (2, 'Dominican'), (3, 'Puerto Rican'), (4, 'South American'), (5, 'Mexican'), (6, 'Other/Hispanic/Latino')], max_length=10, null=True)),
                ('notifications', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('grade_level', models.CharField(blank=True, choices=[('', 'Select'), ('SR', 'Senior - 12th grade'), ('JR', 'Junior- 11th grade'), ('SO', 'Sophomore - 10th grade'), ('FR', 'Freshman - 9th grade')], max_length=2)),
                ('first_gen_student', models.CharField(blank=True, choices=[(1, 'Yes'), (2, 'No')], max_length=2)),
                ('highschool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('do_not_contact', 'Do Not Contact'), ('retired', 'Retired')], default='Active', max_length=100)),
                ('orientation_date', models.DateField(blank=True, null=True)),
                ('orientation_note', models.TextField(blank=True)),
                ('temp_id', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdon', models.DateField()),
                ('status_changed_on', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Approved for FC review', 'Approved for FC review'), ('Decision Made', 'Decision Made'), ('Withdrawn', 'Withdrawn'), ('Closed', 'Closed')], default='In Progress', max_length=30)),
                ('misc_info', models.JSONField(blank=True, null=True)),
                ('highschool_info', models.JSONField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('highschool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['createdon'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('address1', models.CharField(blank=True, max_length=500)),
                ('address2', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=100)),
                ('primary_phone', models.CharField(blank=True, max_length=50)),
                ('emergency_phone', models.CharField(blank=True, max_length=50)),
                ('emergency_contact', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('temp_id', models.IntegerField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.academicyear')),
            ],
            options={
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='TechCenterStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tech_center', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('serving_area', models.CharField(default=13210, max_length=1000)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='TeacherUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('Resume', 'Resume'), ('Transcript', 'Transcript'), ('CV', 'CV'), ('Cover', 'Cover'), ('Other', 'Other')], default='Transcript', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('media', models.FileField(storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.utils.teacher_files_upload_path)),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('parent', models.UUIDField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.utils.teacher_notes_media_upload_path)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.teacher')),
            ],
            options={
                'ordering': ['createdon'],
            },
        ),
        migrations.CreateModel(
            name='TeacherHighSchool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('In the Program', 'In the Program'), ('Not in the Program', 'Not in the Program')], default='In the Program', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('highschool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.teacher')),
            ],
            options={
                'ordering': ['highschool__name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherCourseCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Teaching', 'Teaching'), ('Applicant', 'Applicant'), ('Teaching Substitute', 'Teaching Substitute'), ('Teaching Provisional', 'Teaching Provisional'), ('Do Not Contact', 'Do Not Contact')], default='Teaching', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('since', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.course')),
                ('teacher_highschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cis.teacherhighschool')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherApplicationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('parent', models.UUIDField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('teacher_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.teacherapplication')),
            ],
            options={
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='TeacherApplicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Inactive', 'Inactive')], default='Incomplete', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentSupportingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('media', models.FileField(storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.utils.student_supporting_doc_upload_path)),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.term')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSISError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('match_results', models.JSONField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed')], default='Pending', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('registration_type', models.CharField(choices=[('aspirations', 'Aspirations'), ('bridge', 'Bridge'), ('concurrent', 'Concurrent'), ('other', 'Other')], default='aspirations', max_length=20)),
                ('status', models.CharField(choices=[('applied', 'Requested'), ('approved_by_instructor', 'Approved by Instructor'), ('not_approved_by_instructor', 'Not Approved by Instructor'), ('approved', 'Approved'), ('not_approved', 'Not Approved'), ('missing_prereq', 'Missing PreReq'), ('knowledge_assessment', 'Pending Knowledge Assessment'), ('cancelled', 'Cancelled'), ('section_is_full', 'Section is Full'), ('waitlist', 'Waitlist'), ('late_application', 'Late Application'), ('registered', 'Registered'), ('drop', 'Dropped'), ('wd', 'Withdrawn'), ('app not processed', 'Application Not Processed-See Notes')], default='applied', max_length=100)),
                ('status_changed_on', models.JSONField()),
                ('grade', models.CharField(default='-', max_length=10)),
                ('needs_mirroring', models.BooleanField(blank=True, null=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.classsection')),
                ('highschool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.hsadministrator')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_on', models.DateTimeField(auto_now=True)),
                ('recommendation', models.JSONField()),
                ('upload', models.FileField(blank=True, storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.utils.student_recommendation_upload_path)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.student')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.term')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('parent', models.UUIDField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.utils.student_notes_media_upload_path)),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.student')),
            ],
            options={
                'ordering': ['-createdon'],
            },
        ),
        migrations.CreateModel(
            name='StudentFerpa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campus', models.JSONField()),
                ('permissions_granted', models.JSONField()),
                ('student_signature', models.TextField()),
                ('student_signed_on', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDropRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processed', 'Processed')], default='requested', max_length=20)),
                ('status_changed_on', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cis.studentregistration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cis.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCampusID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.campus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_signature', models.TextField()),
                ('student_signed_on', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.term')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.JSONField(blank=True)),
            ],
            options={
                'unique_together': {('key',)},
            },
        ),
        migrations.CreateModel(
            name='SectionNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('number', models.CharField(max_length=5)),
                ('section_type', models.CharField(choices=[('', '---'), ('Concurrent Enrollment (Academic)', 'Concurrent Enrollment (Academic)'), ('Concurrent Enrollment (Vocational)', 'Concurrent Enrollment (Vocational)'), ('Interactive Video Conference (IVC)', 'Interactive Video Conference (IVC)'), ('Hybrid', 'Hybrid'), ('Face-to-Face (F2F)', 'Face-to-Face (F2F)'), ('Online', 'Online'), ('Career and Technical Education (CTE)', 'Career and Technical Education (CTE)'), ('CTE Richfield Campus', 'CTE Richfield Campus'), ('Online CTE Richfield Campus', 'Online CTE Richfield Campus'), ('CTE Ephraim Campus', 'CTE Ephraim Campus')], max_length=50)),
                ('highschool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_number', models.CharField(max_length=10)),
                ('class_number', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.course')),
                ('high_school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.term')),
            ],
        ),
        migrations.CreateModel(
            name='ParentConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_signature', models.TextField()),
                ('parent_signed_on', models.DateField(blank=True, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=100)),
                ('parent_phone', models.CharField(blank=True, max_length=15)),
                ('parent_email', models.CharField(blank=True, max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.term')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='HSPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('temp_id', models.IntegerField(blank=True, null=True)),
                ('can_manage_class_offering', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=3)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='HSAdministratorPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('since', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('highschool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
                ('hsadmin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.hsadministrator')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.hsposition')),
            ],
        ),
        migrations.CreateModel(
            name='HSAdministratorNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('parent', models.UUIDField(blank=True, null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hsadmin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.hsadministrator')),
            ],
            options={
                'ordering': ['createdon'],
            },
        ),
        migrations.CreateModel(
            name='HSAdministratorAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=100)),
                ('approver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('approver_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('approver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('submittedon', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Submitted', max_length=10)),
                ('highschool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('media', models.FileField(storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.utils.hs_transcript_upload_path)),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
                ('highschool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('parent', models.UUIDField(blank=True, null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('highschool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
            ],
            options={
                'ordering': ['createdon'],
            },
        ),
        migrations.CreateModel(
            name='HighSchoolCollegeAdvisor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('highschool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolClassOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_alias', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.classsection')),
                ('highschool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
            ],
        ),
        migrations.AddField(
            model_name='highschool',
            name='access_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.hsadministrator'),
        ),
        migrations.AddField(
            model_name='highschool',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.district'),
        ),
        migrations.CreateModel(
            name='FutureSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_info', models.JSONField(blank=True)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('future_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cis.futurecourse')),
            ],
        ),
        migrations.AddField(
            model_name='futurecourse',
            name='teacher_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cis.teachercoursecertificate'),
        ),
        migrations.AddField(
            model_name='futurecourse',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.term'),
        ),
        migrations.CreateModel(
            name='FacultyCourseCoordinator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.course')),
                ('faculty_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.facultycoordinator')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCoordinatorNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('parent', models.UUIDField(blank=True, null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('faculty_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.facultycoordinator')),
            ],
            options={
                'ordering': ['createdon'],
            },
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.event')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.speaker')),
            ],
        ),
        migrations.CreateModel(
            name='EventNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('parent', models.UUIDField(blank=True, null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdon'],
            },
        ),
    ]
