# Generated by Django 4.2 on 2024-04-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pd_event', '0001_initial'),
        ('cis', '0001_initial'),
        ('class_visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnote',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pd_event.event'),
        ),
        migrations.AddField(
            model_name='eventitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.event'),
        ),
        migrations.AddField(
            model_name='eventcohort',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.cohort'),
        ),
        migrations.AddField(
            model_name='eventcohort',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventcohort',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.event'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.event'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by_tbd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_tbd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='term_tbd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_tbd', to='cis.term'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.venue'),
        ),
        migrations.AddField(
            model_name='districtadministratorposition',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.district'),
        ),
        migrations.AddField(
            model_name='districtadministratorposition',
            name='district_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.districtadministrator'),
        ),
        migrations.AddField(
            model_name='districtadministratorposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.districtposition'),
        ),
        migrations.AddField(
            model_name='districtadministrator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.college'),
        ),
        migrations.AddField(
            model_name='cronlog',
            name='cron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cis.crontab'),
        ),
        migrations.AddField(
            model_name='courseupload',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.course'),
        ),
        migrations.AddField(
            model_name='coursenote',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.course'),
        ),
        migrations.AddField(
            model_name='coursenote',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseapprequirement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cis.course'),
        ),
        migrations.AddField(
            model_name='courseadministrator',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cis.course'),
        ),
        migrations.AddField(
            model_name='courseadministrator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.campus'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.cohort'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.department'),
        ),
        migrations.AddField(
            model_name='college',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.campus'),
        ),
        migrations.AddField(
            model_name='cohortparticipant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cohortaffiliation',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.cohort'),
        ),
        migrations.AddField(
            model_name='cohortaffiliation',
            name='cohort_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.cohortparticipant'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.department'),
        ),
        migrations.AddField(
            model_name='classvisitreportnote',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classvisitreportnote',
            name='visit_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='class_visit.visitreport'),
        ),
        migrations.AddField(
            model_name='classsectionsyllabi',
            name='class_sections',
            field=models.ManyToManyField(to='cis.classsection'),
        ),
        migrations.AddField(
            model_name='classsectionnote',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.classsection'),
        ),
        migrations.AddField(
            model_name='classsectionnote',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsection',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.campus'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.course'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='highschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.highschool'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.location'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.teacher'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.term'),
        ),
        migrations.AddField(
            model_name='campus',
            name='locations',
            field=models.ManyToManyField(blank=True, to='cis.location'),
        ),
        migrations.AddField(
            model_name='applicationupload',
            name='teacher_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.teacherapplication'),
        ),
        migrations.AddField(
            model_name='applicantschoolcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.course'),
        ),
        migrations.AddField(
            model_name='applicantschoolcourse',
            name='highschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.highschool'),
        ),
        migrations.AddField(
            model_name='applicantschoolcourse',
            name='starting_academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.academicyear'),
        ),
        migrations.AddField(
            model_name='applicantschoolcourse',
            name='teacherapplication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.teacherapplication'),
        ),
        migrations.AddField(
            model_name='applicantrecommendation',
            name='applicantschoolcourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.applicantschoolcourse'),
        ),
        migrations.AddField(
            model_name='applicantrecommendation',
            name='teacher_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.teacherapplication'),
        ),
        migrations.AddField(
            model_name='applicantcoursereviewer',
            name='application_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.applicantschoolcourse'),
        ),
        migrations.AddField(
            model_name='applicantcoursereviewer',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('academic_year', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='techcenterstaff',
            unique_together={('user',)},
        ),
        migrations.AlterUniqueTogether(
            name='teacherhighschool',
            unique_together={('teacher', 'highschool')},
        ),
        migrations.AlterUniqueTogether(
            name='teachercoursecertificate',
            unique_together={('course', 'teacher_highschool')},
        ),
        migrations.AlterUniqueTogether(
            name='studentregistration',
            unique_together={('student', 'class_section')},
        ),
        migrations.AlterUniqueTogether(
            name='studentrecommendation',
            unique_together={('student', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='studentferpa',
            unique_together={('student',)},
        ),
        migrations.AlterUniqueTogether(
            name='studentcampusid',
            unique_together={('student', 'campus', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='studentagreement',
            unique_together={('student', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='sectionnumber',
            unique_together={('number',)},
        ),
        migrations.AlterUniqueTogether(
            name='parentconsent',
            unique_together={('student', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='hsadministratorposition',
            unique_together={('hsadmin', 'highschool', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='highschoolcollegeadvisor',
            unique_together={('highschool', 'advisor')},
        ),
        migrations.AlterUniqueTogether(
            name='highschoolclassoffering',
            unique_together={('highschool', 'class_section')},
        ),
        migrations.AlterUniqueTogether(
            name='highschool',
            unique_together={('name', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='futurecourse',
            unique_together={('teacher_course', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='facultycoursecoordinator',
            unique_together={('faculty_coordinator', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='eventspeaker',
            unique_together={('event', 'speaker')},
        ),
        migrations.AlterUniqueTogether(
            name='eventcohort',
            unique_together={('event', 'cohort')},
        ),
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='districtadministratorposition',
            unique_together={('district_admin', 'district', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'college')},
        ),
        migrations.AlterUniqueTogether(
            name='courseapprequirement',
            unique_together={('course', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('cohort', 'catalog_number', 'campus')},
        ),
        migrations.AlterUniqueTogether(
            name='cohortaffiliation',
            unique_together={('cohort_participant', 'cohort')},
        ),
        migrations.AlterUniqueTogether(
            name='cohort',
            unique_together={('name', 'designator')},
        ),
        migrations.AlterUniqueTogether(
            name='classsection',
            unique_together={('class_number', 'term', 'campus')},
        ),
        migrations.AlterUniqueTogether(
            name='campus',
            unique_together={('name', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='applicantschoolcourse',
            unique_together={('teacherapplication', 'course', 'highschool')},
        ),
        migrations.AlterUniqueTogether(
            name='applicantcoursereviewer',
            unique_together={('reviewer', 'application_course')},
        ),
    ]
