# Generated by Django 4.2 on 2024-05-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
