# Generated by Django 4.2 on 2024-06-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0003_student_parent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
