# Generated by Django 4.2 on 2024-06-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0004_alter_student_parent_phone'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='student',
        #     name='parent_phone',
        # ),
    ]
