# Generated by Django 4.2 on 2024-06-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0005_remove_student_parent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_test',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
