# Generated by Django 4.2 on 2024-08-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0006_student_parent_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercoursecertificate',
            name='highschool_course_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
