# Generated by Django 4.2 on 2024-08-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0007_teachercoursecertificate_highschool_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('nb', 'non-binary')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_identity',
            field=models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('nb', 'non-binary')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_pronoun',
            field=models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('nb', 'non-binary')], default='', max_length=10, null=True),
        ),
    ]
