# Generated by Django 4.2 on 2024-08-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0009_alter_student_gender_alter_student_gender_identity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender_pronoun',
            field=models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('nb', 'non-binary'), ('other', 'Other')], default='', max_length=20, null=True),
        ),
    ]
