# Generated by Django 4.2 on 2024-08-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0010_alter_student_gender_pronoun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('n', 'Prefer to Self-Describe')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_identity',
            field=models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('n', 'Prefer to Self-Describe')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_pronoun',
            field=models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('n', 'Prefer to Self-Describe')], default='', max_length=20, null=True),
        ),
    ]
