# Generated by Django 4.2 on 2024-08-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0011_alter_student_gender_alter_student_gender_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='highschool_course_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
