# Generated by Django 4.2 on 2024-08-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0012_classsection_highschool_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='co_reqs',
            field=models.ManyToManyField(blank=True, null=True, to='cis.classsection'),
        ),
    ]
