# Generated by Django 4.2 on 2024-09-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0013_classsection_co_reqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='psid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='code',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
