# Generated by Django 4.2 on 2024-09-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0014_alter_customuser_psid_alter_highschool_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alt_username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
