# Generated by Django 4.2 on 2024-09-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0015_customuser_alt_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='sis_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
