# Generated by Django 4.2 on 2024-09-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0016_studentregistration_sis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='sis_log',
            field=models.ManyToManyField(blank=True, to='cis.sis_log'),
        ),
    ]
