# Generated by Django 4.2 on 2024-10-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0017_studentregistration_sis_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sis_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
