# Generated by Django 4.2 on 2024-11-28 18:26

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0018_alter_student_sis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='co_reqs',
            field=models.ManyToManyField(blank=True, to='cis.classsection'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='student',
            name='ethnicity',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'American Indian/Alaska Native'), (2, 'Asian'), (3, 'Black/African American'), (4, 'Native Hawaiian/Other Pacific Islander'), (5, 'White')], max_length=20),
        ),
    ]
