# Generated by Django 4.2 on 2025-05-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0019_alter_classsection_co_reqs_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('C', 'Cancelled')], default='active', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('1', 'Nonbinary/Gender Nonconforming'), ('2', 'Other'), ('3', 'Transgender'), ('4', 'Unknown/Not Provided/Prefer Not to Answer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_identity',
            field=models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('1', 'Nonbinary/Gender Nonconforming'), ('2', 'Other'), ('3', 'Transgender'), ('4', 'Unknown/Not Provided/Prefer Not to Answer')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_pronoun',
            field=models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('1', 'Nonbinary/Gender Nonconforming'), ('2', 'Other'), ('3', 'Transgender'), ('4', 'Unknown/Not Provided/Prefer Not to Answer')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent1_education_level',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('1', 'Unknown'), ('2', 'High school/GED'), ('3', 'Some college'), ('4', "Associate's degree"), ('5', "Bachelor's degree"), ('6', 'Graduate Degree or higher')], max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent2_education_level',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('1', 'Unknown'), ('2', 'High school/GED'), ('3', 'Some college'), ('4', "Associate's degree"), ('5', "Bachelor's degree"), ('6', 'Graduate Degree or higher')], max_length=2),
        ),
    ]
