# Generated by Django 4.2 on 2025-06-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0020_alter_classsection_status_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='note',
            field=models.TextField(blank=True, help_text='Note of the registration status', null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='status',
            field=models.CharField(choices=[('applied', 'Requested'), ('approved_by_instructor', 'Approved by Instructor'), ('not_approved_by_instructor', 'Not Approved by Instructor'), ('approved', 'Approved'), ('not_approved', 'Not Approved'), ('missing_prereq', 'Missing PreReq'), ('knowledge_assessment', 'Pending Knowledge Assessment'), ('cancelled', 'Cancelled'), ('section_is_full', 'Section is Full'), ('waitlist', 'Waitlist'), ('late_application', 'Late Application'), ('registered', 'Registered'), ('RE', 'RE'), ('drop', 'Dropped'), ('wd', 'Withdrawn'), ('app not processed', 'Application Not Processed-See Notes')], default='applied', max_length=100),
        ),
    ]
