# Generated by Django 4.2 on 2025-06-25 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0021_studentregistration_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='highschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.highschool'),
        ),
    ]
