# Generated by Django 4.2 on 2025-07-10 13:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0022_alter_studentregistration_highschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='hs_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', ''), ('Students Pay', 'Students Pay'), ('District pays for SOME students', 'District pays for SOME students'), ('District pays for ALL students', 'District pays for ALL students'), ('Pseudo District Pay', 'Pseudo District Pay')], max_length=150),
        ),
    ]
