# Generated by Django 4.2 on 2025-07-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0023_alter_highschool_hs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='sau',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
