# Generated by Django 4.2 on 2025-07-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0024_alter_highschool_sau'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='suffix',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
