# Generated by Django 4.2 on 2025-08-08 15:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0026_course_registration_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registration_eligibility',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SR', 'Senior - 12th grade'), ('SR*', 'Senior - 12th grade with recommendation'), ('JR', 'Junior- 11th grade'), ('JR*', 'Junior- 11th grade with recommendation'), ('SO', 'Sophomore - 10th grade'), ('SO*', 'Sophomore - 10th grade with recommendation'), ('FR', 'Freshman - 9th grade'), ('FR*', 'Freshman - 9th grade with recommendation')], default=['SR', 'JR'], max_length=100),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='hs_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', ''), ('PA Public High Schools', 'PA Public High Schools'), ('PA, Religious or Private Schools', 'PA, Religious or Private Schools'), ('All Other States', 'All Other States')], max_length=150),
        ),
    ]
