# Generated by Django 4.2 on 2025-08-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0027_alter_course_registration_eligibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='tuition',
            field=models.FloatField(default=0),
        ),
    ]
