# Generated by Django 4.2 on 2025-08-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0028_classsection_tuition'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='non_student_pay_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='pay_type',
            field=models.CharField(choices=[('', '---'), ('student', 'Student Pay'), ('school_full', 'School Full Pay'), ('school_partial', 'School Partial Pay'), ('frl', 'Free or Reduced Lunch')], default='', max_length=20),
        ),
    ]
