# Generated by Django 4.2 on 2025-08-14 15:01

import cis.storage_backend
import cis.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0029_studentregistration_non_student_pay_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTuitionAssistance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('information', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('Not Yet Submitted', 'Not Yet Submitted'), ('Submitted', 'Submitted'), ('Pending Review', 'Pending Review'), ('Needs Information', 'Needs Information'), ('Processed', 'Processed')], default='', max_length=50)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('updated_on', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='current_school_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='current_student_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_last_reviewed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_last_reviewed', to='cis.term'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent1_education_level',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('1', 'Unknown'), ('2', 'High school/GED'), ('3', 'Some college, no degree'), ('4', 'Associate degree (e.g., AA, AS)'), ('5', "Bachelor's degree (e.g., BA, BS)"), ('6', 'Some graduate school, no degree'), ('7', 'Graduate Degree or higher'), ('8', 'Unknown / Prefer not to answer')], max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent2_education_level',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('1', 'Unknown'), ('2', 'High school/GED'), ('3', 'Some college, no degree'), ('4', 'Associate degree (e.g., AA, AS)'), ('5', "Bachelor's degree (e.g., BA, BS)"), ('6', 'Some graduate school, no degree'), ('7', 'Graduate Degree or higher'), ('8', 'Unknown / Prefer not to answer')], max_length=2),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='status',
            field=models.CharField(choices=[('applied', 'Requested'), ('approved', 'Approved'), ('not_approved', 'Not Approved'), ('missing_prereq', 'Missing PreReq'), ('knowledge_assessment', 'Pending Knowledge Assessment'), ('cancelled', 'Cancelled'), ('section_is_full', 'Section is Full'), ('waitlist', 'Waitlist'), ('late_application', 'Late Application'), ('pending_registration', 'Pending Registration'), ('registered', 'Registered'), ('drop', 'Dropped'), ('wd', 'Withdrawn'), ('app not processed', 'Application Not Processed-See Notes')], default='applied', max_length=100),
        ),
        migrations.CreateModel(
            name='StudentTuitionAssistanceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('media', models.FileField(storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.utils.student_tuition_assistance_upload_path)),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
                ('tuition_assistance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cis.studenttuitionassistance')),
            ],
        ),
        migrations.AddField(
            model_name='studenttuitionassistance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.student'),
        ),
        migrations.AddField(
            model_name='studenttuitionassistance',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.term'),
        ),
        migrations.AlterUniqueTogether(
            name='studenttuitionassistance',
            unique_together={('student', 'term')},
        ),
    ]
