# Generated by Django 4.2 on 2025-08-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0030_studenttuitionassistance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='dates',
            field=models.JSONField(default=dict),
        ),
    ]
