# Generated by Django 4.2 on 2025-08-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0031_term_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
