# Generated by Django 4.2 on 2025-08-27 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0032_customuser_last_updated_on_student_last_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cte_students', to='cis.highschool'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('u', 'Undisclosed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_identity',
            field=models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('u', 'Undisclosed')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_pronoun',
            field=models.CharField(choices=[('', 'Select'), ('m', 'Male'), ('f', 'Female'), ('u', 'Undisclosed')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='pay_type',
            field=models.CharField(choices=[('', '---'), ('student', 'Student Pay'), ('school_full', 'School Full Pay'), ('school_partial', 'School Partial Pay')], default='', max_length=20),
        ),
    ]
