# Generated by Django 4.2 on 2025-09-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0033_student_cte_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='registration_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_term', to='cis.term', verbose_name='Registration Term'),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('C', 'Cancelled')], default='A', max_length=30, null=True),
        ),
    ]
