# Generated by Django 4.2 on 2025-09-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0034_classsection_registration_term_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='student',
        #     name='parent2_education_level',
        # ),
    ]
