# Generated by Django 4.2 on 2025-10-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0036_highschool_hs_pay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='hs_pay_type',
            field=models.CharField(blank=True, choices=[('', ''), ('Student Pay', 'Student Pay'), ('School Full Pay', 'School Full Pay'), ('School Partial Pay', 'School Partial Pay')], default='Student Pay', max_length=150, verbose_name='High School Pay Type'),
        ),
    ]
