# Generated by Django 4.2 on 2025-10-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0037_alter_highschool_hs_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('not_verified', 'Not Verified'), ('enrolled', 'Enrolled'), ('not_enrolled', 'Not Enrolled')], default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='verified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
