# Generated by Django 4.2 on 2026-01-03 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0038_studentregistration_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurecourse',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='status',
            field=models.CharField(choices=[('applied', 'Requested'), ('approved', 'Ready for SHU Review'), ('not_approved', 'Not Approved by HS'), ('missing_prereq', 'Missing PreReq'), ('pending_registration', 'Approved for Registration'), ('denied_registration', 'Not Approved for Registration'), ('registered', 'Registered'), ('enrolled', 'Enrolled'), ('drop', 'Dropped'), ('wd', 'Withdrawn'), ('app not processed', 'Application Not Processed-See Notes')], default='applied', max_length=100),
        ),
        migrations.CreateModel(
            name='FutureProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta', models.JSONField(default=dict)),
                ('started_on', models.DateField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('highschool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
            ],
            options={
                'unique_together': {('academic_year', 'highschool')},
            },
        ),
    ]
