# Generated by Django 5.2.10 on 2026-02-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0039_futurecourse_meta_alter_studentregistration_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highschool',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
