# Generated by Django 5.2.12 on 2026-03-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0042_historicalcustomuser_historicalstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='sis_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='term',
            name='sis_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
