# Generated by Django 5.2.12 on 2026-03-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0043_academicyear_meta_academicyear_sis_id_term_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
