# Generated by Django 5.2.12 on 2026-03-13 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0045_cohort_created_at_cohort_external_sis_id_cohort_meta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicyear',
            old_name='sis_id',
            new_name='external_sis_id',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='sis_id',
            new_name='external_sis_id',
        ),
    ]
