# Generated by Django 5.2.12 on 2026-03-15 21:07

import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0046_rename_sis_id_academicyear_external_sis_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='external_sis_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='HistoricalCourse',
            fields=[
                ('external_sis_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('catalog_number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_hours', models.FloatField(default=1)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('teacher_requirement', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prereq', models.TextField(blank=True, null=True, verbose_name='Pre-reqs')),
                ('stream', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Humanities', 'Humanities & Social Sciences'), ('Languages', 'Languages'), ('STEM', 'STEM'), ('Business & Tech.', 'Business & Tech.')], max_length=100)),
                ('registration_eligibility', multiselectfield.db.fields.MultiSelectField(choices=[('SR', 'Senior - 12th grade'), ('SR*', 'Senior - 12th grade with recommendation'), ('JR', 'Junior- 11th grade'), ('JR*', 'Junior- 11th grade with recommendation'), ('SO', 'Sophomore - 10th grade'), ('SO*', 'Sophomore - 10th grade with recommendation'), ('FR', 'Freshman - 9th grade'), ('FR*', 'Freshman - 9th grade with recommendation')], default=['SR', 'JR'], max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('temp_id', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('campus', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.campus')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.category')),
                ('cohort', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.cohort')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical course',
                'verbose_name_plural': 'historical courses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
