# Generated by Django 5.2.12 on 2026-03-30 15:03

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0047_course_created_at_course_external_sis_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classsection',
            name='external_sis_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classsection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='HistoricalClassSection',
            fields=[
                ('external_sis_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('class_number', models.IntegerField()),
                ('section_number', models.CharField(max_length=5)),
                ('highschool_course_title', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('highschool_course_name', models.CharField(blank=True, max_length=500)),
                ('credit_hours', models.FloatField(default=1)),
                ('days', models.CharField(blank=True, max_length=50)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('instruction_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('prereq', models.TextField(blank=True)),
                ('max_enrollment', models.IntegerField(default=0)),
                ('min_enrollment', models.IntegerField(default=0)),
                ('lab_fees', models.FloatField(default=0)),
                ('tuition', models.FloatField(default=0)),
                ('enrollment', models.IntegerField(default=0)),
                ('available_seats', models.IntegerField(default=0)),
                ('last_imported_on', models.DateField(blank=True, editable=False)),
                ('room_alias', models.CharField(blank=True, max_length=10, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('notifications', models.JSONField(blank=True, null=True)),
                ('period_time', models.CharField(blank=True, max_length=500, null=True)),
                ('free_period', models.CharField(blank=True, max_length=500, null=True)),
                ('roster_status', models.CharField(blank=True, choices=[('', ''), ('pending verification', 'Pending Verification'), ('accurate', 'Accurate'), ('inaccurate', 'Inaccurate')], default='', max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Active'), ('C', 'Cancelled')], default='A', max_length=30, null=True)),
                ('roster_status_changed_on', models.JSONField(blank=True, null=True)),
                ('syllabi_status', models.CharField(blank=True, choices=[('', ''), ('pending review', 'Pending Review'), ('reviewed', 'Reviewed'), ('needs update', 'Needs Update')], default='', max_length=30, null=True)),
                ('syllabi_status_changed_on', models.JSONField(default=dict)),
                ('grade_status', models.CharField(blank=True, choices=[('', 'N/A'), ('saved', 'Grades Saved Only'), ('submitted', 'Grades Successfully Submitted')], default='', max_length=30, null=True)),
                ('grade_status_changed_on', models.JSONField(blank=True, null=True)),
                ('part_of_term', models.CharField(blank=True, max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('campus', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.campus')),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.course')),
                ('highschool', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.highschool')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.location')),
                ('registration_term', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.term', verbose_name='Registration Term')),
                ('teacher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.teacher')),
                ('term', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.term')),
            ],
            options={
                'verbose_name': 'historical class section',
                'verbose_name_plural': 'historical class sections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
