# Generated by Django 5.2.12 on 2026-03-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0047_course_created_at_course_external_sis_id_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='classsection',
        #     name='class_number',
        #     field=models.CharField(max_length=50),
        # ),
    ]
