# Generated by Django 5.2.12 on 2026-03-31 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0048_alter_classsection_class_number'),
        ('cis', '0048_classsection_created_at_classsection_external_sis_id_and_more'),
    ]

    operations = [
    ]
