# Generated by Django 5.2.12 on 2026-04-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0050_ethos_resource_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ethosresource',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ethosresource',
            name='application',
        ),
        migrations.RemoveField(
            model_name='ethosrepresentation',
            name='resource',
        ),
        migrations.DeleteModel(
            name='EthosApplication',
        ),
        migrations.DeleteModel(
            name='EthosRepresentation',
        ),
        migrations.DeleteModel(
            name='EthosResource',
        ),
    ]
