# Generated by Django 5.2.13 on 2026-04-15 09:15

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0051_delete_ethos_resource_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='ethnicity',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'American Indian/Alaska Native'), (2, 'Asian'), (3, 'Black/African American'), (4, 'Native Hawaiian/Other Pacific Islander'), (5, 'White')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='ethnicity',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'American Indian/Alaska Native'), (2, 'Asian'), (3, 'Black/African American'), (4, 'Native Hawaiian/Other Pacific Islander'), (5, 'White')], max_length=200),
        ),
    ]
