# Generated by Django 5.2.13 on 2026-04-21 10:38

import re

from django.db import migrations, models


def backfill_application_status(apps, schema_editor):
    """
    Backfill rules:
      - account_verified=False              -> 'draft'
      - highschool assigned                 -> 'pending'
      - sis_sent_on set (and no real psid)  -> 'in_review'
      - user.psid matches id_verify_regex   -> 'accepted'
    """
    Student = apps.get_model('cis', 'Student')
    Setting = apps.get_model('cis', 'Setting')

    try:
        email_setting = Setting.objects.filter(key__endswith='registration_email').first()
        pattern = (email_setting.value or {}).get('id_verify_regex', r'^H\d{7}$') if email_setting else r'^H\d{7}$'
    except Exception:
        pattern = r'^H\d{7}$'

    try:
        compiled = re.compile(pattern)
    except re.error:
        compiled = re.compile(r'^H\d{7}$')

    for student in Student.objects.select_related('user').iterator():
        psid = (student.user.psid or '').strip() if student.user else ''
        if psid and psid != '-' and compiled.match(psid):
            status = 'accepted'
        elif student.sis_sent_on:
            status = 'in_review'
        elif student.highschool_id:
            status = 'pending'
        elif not student.account_verified:
            status = 'draft'
        else:
            status = 'pending' if student.highschool_id else 'draft'

        if student.application_status != status:
            student.application_status = status
            student.save(update_fields=['application_status'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0052_alter_historicalstudent_ethnicity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='application_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_review', 'In Review'), ('accepted', 'Accepted')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='application_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_review', 'In Review'), ('accepted', 'Accepted')], db_index=True, default='draft', max_length=20),
        ),
        migrations.RunPython(backfill_application_status, reverse_noop),
    ]
