# Generated by Django 5.2.13 on 2026-04-22 18:43

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0054_rename_cron_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='ethnicity',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'American Indian or Alaska Native'), (2, 'Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander'), (5, 'White')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='ethnicity',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'American Indian or Alaska Native'), (2, 'Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander'), (5, 'White')], max_length=200),
        ),
    ]
