# Generated by Django 5.2.14 on 2026-05-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0055_alter_historicalstudent_ethnicity_and_more'),
        ('ethos', '0003_resource_preferred_representation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='last_mirror_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='last_mirror_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='last_mirror_status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, help_text='Outcome of the most recent mirror_to_sis attempt', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='mirror_logs',
            field=models.ManyToManyField(blank=True, related_name='student_registrations', to='ethos.ethoslog'),
        ),
    ]
