# Generated by Django 5.2.14 on 2026-05-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0056_studentregistration_mirror_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-academic_year__name', '-code']},
        ),
        migrations.AlterField(
            model_name='classsection',
            name='section_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='courseadministrator',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Faculty', 'Faculty'), ('FC Reviewer', 'FC Reviewer'), ('Visitor', 'Visitor'), ('Dept. Chair', 'Dept. Chair'), ('Dean', 'Dean')], default='Administrator', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalclasssection',
            name='section_number',
            field=models.CharField(max_length=10),
        ),
    ]
