# Generated by Django 5.2.14 on 2026-05-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0057_alter_term_options_alter_classsection_section_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='profile_dirty_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the student edits their own profile. Cleared by staff after review.', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_dirty_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the student edits their own profile. Cleared by staff after review.', null=True),
        ),
    ]
