# Generated by Django 5.2.14 on 2026-06-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0058_student_profile_dirty_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='class_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalclasssection',
            name='class_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='status',
            field=models.CharField(choices=[('applied', 'Requested'), ('approved', 'Ready for Review'), ('not_approved', 'Not Approved by HS'), ('missing_prereq', 'Missing PreReq'), ('pending_registration', 'Approved for Registration'), ('denied_registration', 'Not Approved for Registration'), ('registered', 'Registered'), ('enrolled', 'Enrolled'), ('drop', 'Dropped'), ('wd', 'Withdrawn'), ('app not processed', 'Application Not Processed-See Notes')], default='applied', max_length=100),
        ),
    ]
