# Generated by Django 5.2.14 on 2026-06-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0059_alter_classsection_class_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='account_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
