# Generated by Django 5.2.15 on 2026-06-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0060_customuser_account_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercoursecertificate',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachercoursecertificate',
            name='last_reminder_sent_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachercoursecertificate',
            name='last_renewed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachercoursecertificate',
            name='renewal_required_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
