# Generated by Django 5.2.15 on 2026-06-17 17:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0061_teachercoursecertificate_expires_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('scope', models.CharField(choices=[('ce', 'CE Admin'), ('highschool_admin', 'High School Admin')], default='ce', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('committed', 'Committed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('duplicate', 'Duplicate (skipped)'), ('error', 'Error')], default='error', max_length=20)),
                ('errors', models.JSONField(blank=True, default=dict)),
                ('selected', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, default='', max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='cis.studentimportbatch')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
