# Generated by Django 5.2.15 on 2026-06-21 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0062_studentimportbatch_studentimportrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEnrollBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('committed', 'Committed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.term')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkEnrollRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('section_label', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('duplicate', 'Already enrolled (skipped)'), ('error', 'Error')], default='error', max_length=20)),
                ('errors', models.JSONField(blank=True, default=dict)),
                ('selected', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, default='', max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='cis.bulkenrollbatch')),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.classsection')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.student')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
