# Generated by Django 5.2.15 on 2026-07-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0064_add_support_ticket_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsupportingdocument',
            name='document_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentsupportingdocument',
            name='status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
