# Generated by Django 5.2.15 on 2026-07-09 08:33

import django.db.models.deletion
import multiselectfield.db.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0065_studentsupportingdocument_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHighSchool',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(default='-', max_length=20)),
                ('sau', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('address1', models.CharField(blank=True, max_length=500)),
                ('address2', models.CharField(blank=True, max_length=500)),
                ('po_box', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=50)),
                ('secondary_phone', models.CharField(blank=True, max_length=50)),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('temp_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('', '---'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30)),
                ('state_code', models.CharField(blank=True, max_length=10)),
                ('hs_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', ''), ('PA Public High Schools', 'PA Public High Schools'), ('PA, Religious or Private Schools', 'PA, Religious or Private Schools'), ('All Other States', 'All Other States')], max_length=150)),
                ('hs_pay_type', models.CharField(blank=True, choices=[('', ''), ('Student Pay', 'Student Pay'), ('School Full Pay', 'School Full Pay'), ('School Partial Pay', 'School Partial Pay')], default='Student Pay', max_length=150, verbose_name='High School Pay Type')),
                ('oncampus_sections', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('access_approver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.hsadministrator')),
                ('district', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.district')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical high school',
                'verbose_name_plural': 'historical high schools',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStudentRegistration',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('verified_on', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('not_verified', 'Not Verified'), ('enrolled', 'Enrolled'), ('not_enrolled', 'Not Enrolled')], default='pending', max_length=20, null=True)),
                ('pay_type', models.CharField(choices=[('', '---'), ('student', 'Student Pay'), ('school_full', 'School Full Pay'), ('school_partial', 'School Partial Pay')], default='', max_length=20)),
                ('non_student_pay_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('registration_type', models.CharField(choices=[('aspirations', 'Aspirations'), ('bridge', 'Bridge'), ('concurrent', 'Concurrent'), ('other', 'Other')], default='aspirations', max_length=20)),
                ('status', models.CharField(choices=[('applied', 'Requested'), ('approved', 'Ready for Review'), ('not_approved', 'Not Approved by HS'), ('missing_prereq', 'Missing PreReq'), ('pending_registration', 'Approved for Registration'), ('denied_registration', 'Not Approved for Registration'), ('registered', 'Registered'), ('enrolled', 'Enrolled'), ('drop', 'Dropped'), ('wd', 'Withdrawn'), ('app not processed', 'Application Not Processed-See Notes')], default='applied', max_length=100)),
                ('status_changed_on', models.JSONField()),
                ('note', models.TextField(blank=True, help_text='Note of the registration status', null=True)),
                ('grade', models.CharField(default='-', max_length=10)),
                ('needs_mirroring', models.BooleanField(blank=True, null=True)),
                ('sis_id', models.UUIDField(blank=True, default=None, null=True)),
                ('last_mirror_status', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, help_text='Outcome of the most recent mirror_to_sis attempt', max_length=10, null=True)),
                ('last_mirror_error', models.TextField(blank=True, default='')),
                ('last_mirror_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('class_section', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.classsection')),
                ('highschool', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.highschool')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.hsadministrator')),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.student')),
            ],
            options={
                'verbose_name': 'historical student registration',
                'verbose_name_plural': 'historical student registrations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
