# Generated by Django 5.2.16 on 2026-07-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0068_term_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherupload',
            name='media_type',
            field=models.CharField(choices=[('Resume', 'Resume'), ('Transcript', 'Transcript'), ('CV', 'CV'), ('Cover', 'Cover'), ('Certificate', 'Certificate'), ('PD Letter', 'PD Letter'), ('Other', 'Other')], default='Transcript', max_length=30),
        ),
    ]
