# Generated by Django 5.2.16 on 2026-07-14 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0069_alter_teacherupload_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_years', to='cis.campus'),
        ),
    ]
