# Generated by Django 5.2.16 on 2026-07-15 11:01

from django.db import migrations, models


# Registration-status value renames applied by this migration.
STATUS_RENAMES = {'drop': 'dropped', 'wd': 'withdrawn'}
STATUS_RENAMES_REVERSE = {v: k for k, v in STATUS_RENAMES.items()}


def _remap_settings(Setting, mapping):
    """Rewrite stored status values inside every Setting JSON blob.

    Three shapes hold registration-status values:
      * list-valued trigger fields (sis_mirror_trigger, parent_trigger,
        student_trigger, charge_trigger, charge_remove_trigger, and the same
        MultipleChoiceField(choices=STATUS_OPTIONS) fields in the other
        settings) — remap exact list members;
      * dynamic per-status keys in *_regis_status_email
        (status_change_<status>_subject / _email) — rename the key prefix.
    Scalar string values (email bodies, is_active, etc.) are left untouched.
    """
    for setting in Setting.objects.all():
        value = setting.value
        if not isinstance(value, dict):
            continue

        changed = False
        new_value = {}
        for key, val in value.items():
            new_key = key
            for old, new in mapping.items():
                prefix = f'status_change_{old}_'
                if key.startswith(prefix):
                    new_key = f'status_change_{new}_' + key[len(prefix):]
                    changed = True
                    break

            if isinstance(val, list):
                remapped = [mapping.get(item, item) if isinstance(item, str) else item
                            for item in val]
                if remapped != val:
                    changed = True
                    val = remapped

            new_value[new_key] = val

        if changed:
            setting.value = new_value
            setting.save(update_fields=['value'])


def _remap_registration_status(apps, mapping):
    StudentRegistration = apps.get_model('cis', 'StudentRegistration')
    HistoricalStudentRegistration = apps.get_model('cis', 'HistoricalStudentRegistration')
    for old, new in mapping.items():
        StudentRegistration.objects.filter(status=old).update(status=new)
        HistoricalStudentRegistration.objects.filter(status=old).update(status=new)


def forwards(apps, schema_editor):
    _remap_registration_status(apps, STATUS_RENAMES)
    _remap_settings(apps.get_model('cis', 'Setting'), STATUS_RENAMES)


def backwards(apps, schema_editor):
    _remap_registration_status(apps, STATUS_RENAMES_REVERSE)
    _remap_settings(apps.get_model('cis', 'Setting'), STATUS_RENAMES_REVERSE)


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0070_academicyear_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentregistration',
            name='status',
            field=models.CharField(choices=[('applied', 'Requested'), ('approved', 'Ready for Review'), ('not_approved', 'Not Approved by HS'), ('missing_prereq', 'Missing PreReq'), ('pending_registration', 'Approved for Registration'), ('denied_registration', 'Not Approved for Registration'), ('registered', 'Registered'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped'), ('withdrawn', 'Withdrawn'), ('app not processed', 'Application Not Processed-See Notes')], default='applied', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='status',
            field=models.CharField(choices=[('applied', 'Requested'), ('approved', 'Ready for Review'), ('not_approved', 'Not Approved by HS'), ('missing_prereq', 'Missing PreReq'), ('pending_registration', 'Approved for Registration'), ('denied_registration', 'Not Approved for Registration'), ('registered', 'Registered'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped'), ('withdrawn', 'Withdrawn'), ('app not processed', 'Application Not Processed-See Notes')], default='applied', max_length=100),
        ),
        migrations.RunPython(forwards, backwards),
    ]
