# Generated by Django 5.2.16 on 2026-07-31 14:18

import cis.models.highschool
import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0072_profile_field_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='hs_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=cis.models.highschool.hs_type_choices, max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalhighschool',
            name='hs_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=cis.models.highschool.hs_type_choices, max_length=150),
        ),
    ]
