# Generated by Django 5.2.16 on 2026-08-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0073_alter_highschool_hs_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentregistration',
            name='status',
            field=models.CharField(choices=[('applied', 'Requested'), ('approved', 'Ready for Review'), ('not_approved', 'Not Approved by HS'), ('missing_prereq', 'Missing PreReq'), ('duplicate', 'Duplicate Section'), ('pending_registration', 'Approved for Registration'), ('denied_registration', 'Not Approved for Registration'), ('registered', 'Registered'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped'), ('withdrawn', 'Withdrawn'), ('app not processed', 'Application Not Processed-See Notes')], default='applied', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='status',
            field=models.CharField(choices=[('applied', 'Requested'), ('approved', 'Ready for Review'), ('not_approved', 'Not Approved by HS'), ('missing_prereq', 'Missing PreReq'), ('duplicate', 'Duplicate Section'), ('pending_registration', 'Approved for Registration'), ('denied_registration', 'Not Approved for Registration'), ('registered', 'Registered'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped'), ('withdrawn', 'Withdrawn'), ('app not processed', 'Application Not Processed-See Notes')], default='applied', max_length=100),
        ),
    ]
