# Generated by Django 5.2.16 on 2026-08-11 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0077_refresh_grade_levels_cron_and_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyTeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_teacher_assignments', to='cis.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_teacher_assignments', to='cis.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_teacher_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='cis.teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_teacher_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'course', 'academic_year'], name='cis_fta_user_course_year_idx')],
                'unique_together': {('user', 'course', 'teacher', 'academic_year')},
            },
        ),
    ]
