# Generated by Django 5.2.17 on 2026-09-07 18:56

import cis.models.course
import django.db.models.deletion
import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0078_facultyteacherassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDocumentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.CharField(choices=cis.models.course.course_document_choices, max_length=100)),
                ('grade_levels', multiselectfield.db.fields.MultiSelectField(blank=True, choices=cis.models.course.student_grade_choices, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('required', models.CharField(choices=[('', 'Select'), ('1', 'Yes'), ('2', 'No')], default=1, max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cis.course')),
            ],
            options={
                'unique_together': {('course', 'document')},
            },
        ),
    ]
