# Generated by Django 5.2.17 on 2026-09-23 00:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0080_add_locked_accounts_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.campus')),
            ],
            options={
                'ordering': ['label'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('campus__isnull', True)), fields=('code',), name='documenttype_unique_code_unassigned'), models.UniqueConstraint(condition=models.Q(('campus__isnull', False)), fields=('campus', 'code'), name='documenttype_unique_code_per_campus')],
            },
        ),
    ]
