# Generated by Django 5.2.17 on 2026-09-23 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0081_documenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedocumentrequirement',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.documenttype'),
        ),
        migrations.AddField(
            model_name='studentsupportingdocument',
            name='document_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.documenttype'),
        ),
    ]
