# Generated by Django 5.2.17 on 2026-09-27 22:35

from django.db import migrations, models
from django.utils import timezone


def stamp_existing_locks(apps, schema_editor):
    """Give accounts already locked a lock time of now.

    Without it they have no timestamp and never time out; with it they release
    ACCOUNT_LOCKOUT_MINUTES after the deploy, where the tenant has opted in.
    """
    CustomUser = apps.get_model('cis', 'CustomUser')
    CustomUser.objects.filter(
        account_locked=True, account_locked_at__isnull=True
    ).update(account_locked_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0082_document_type_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='account_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(stamp_existing_locks, migrations.RunPython.noop),
    ]
