# Generated by Django 5.2.17 on 2026-09-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0084_add_document_types_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedocumentrequirement',
            name='recurrence',
            field=models.CharField(choices=[('per_term', 'Once per term'), ('per_academic_year', 'Once per academic year'), ('once', 'Once per student')], default='per_term', max_length=20),
        ),
    ]
