# Generated by Django 5.2.17 on 2026-09-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0085_coursedocumentrequirement_recurrence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SIS_Subscription',
        ),
    ]
