# Generated by Django 5.2.17 on 2026-09-28 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0086_delete_sis_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschooltranscript',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='highschooltranscript',
            name='reviewed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highschooltranscript',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.term'),
        ),
        migrations.AlterField(
            model_name='highschooltranscript',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
