# Generated by Django 5.2.17 on 2026-09-29 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0088_campus_site'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cohort',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cohort',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='cis.campus'),
        ),
        migrations.AddField(
            model_name='historicalcohort',
            name='campus',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.campus'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', True)), fields=('name',), name='academicyear_unique_name_unassigned'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', False)), fields=('campus', 'name'), name='academicyear_unique_name_per_campus'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', True)), fields=('name', 'designator'), name='cohort_unique_name_designator_unassigned'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', False)), fields=('campus', 'name', 'designator'), name='cohort_unique_name_designator_per_campus'),
        ),
        migrations.AddConstraint(
            model_name='college',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', True)), fields=('name',), name='college_unique_name_unassigned'),
        ),
        migrations.AddConstraint(
            model_name='college',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', False)), fields=('campus', 'name'), name='college_unique_name_per_campus'),
        ),
    ]
