# Generated by Django 5.2.17 on 2026-09-29 02:39

from django.db import migrations


SSN_PERMISSIONS = (('view_ssn', 'Can view SSN'), ('change_ssn', 'Can change SSN'))


def grant_ssn_permissions_to_ce(apps, schema_editor):
    """Existing CE staff keep the SSN access they have today (MC-14).

    Granted to the `ce` group, so it follows group membership; individual
    exceptions are managed per user afterwards. Django only creates a model's
    permissions after migrate finishes, so create the two rows here.
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    content_type, _ = ContentType.objects.get_or_create(app_label='cis', model='customuser')
    perms = [
        Permission.objects.get_or_create(
            content_type=content_type, codename=codename, defaults={'name': name})[0]
        for codename, name in SSN_PERMISSIONS
    ]
    for group in Group.objects.filter(name='ce'):
        group.permissions.add(*perms)


def revoke_ssn_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    perms = Permission.objects.filter(
        content_type__app_label='cis', codename__in=['view_ssn', 'change_ssn'])
    for group in Group.objects.filter(name='ce'):
        group.permissions.remove(*perms)


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0089_campus_scoped_unique_names'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name'], 'permissions': [('create_user', 'Can create new user'), ('view_ssn', 'Can view SSN'), ('change_ssn', 'Can change SSN')]},
        ),
        migrations.RunPython(grant_ssn_permissions_to_ce, revoke_ssn_permissions),
    ]
