# Generated by Django 5.2.17 on 2026-09-29 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0090_ssn_permissions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalsetting',
            name='campus',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.campus'),
        ),
        migrations.AddField(
            model_name='setting',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='cis.campus'),
        ),
        migrations.AlterField(
            model_name='historicalsetting',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', True)), fields=('key',), name='setting_unique_key_global'),
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', False)), fields=('campus', 'key'), name='setting_unique_key_per_campus'),
        ),
    ]
