# Generated by Django 5.2.17 on 2026-09-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0091_setting_campus'),
        # The IdP table exists from sp's first migration; depending on a later one
        # would tie cis to one django-saml-sp version.
        ('sp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='saml_idps',
            field=models.ManyToManyField(blank=True, related_name='campuses', to='sp.idp'),
        ),
    ]
