# Generated by Django 5.2.17 on 2026-09-29 03:18

import uuid

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Mirror every user's campus['process_campus'] into the new M2M.

    Adds rows only; the JSON is left as it is. Ids of campuses that no
    longer exist are skipped.
    """
    User = apps.get_model('cis', 'CustomUser')
    Campus = apps.get_model('cis', 'Campus')
    known = {str(pk) for pk in Campus.objects.values_list('id', flat=True)}
    through = User.process_campuses.through
    rows = []
    for user_id, perms in User.objects.filter(
            campus__has_key='process_campus').values_list('id', 'campus'):
        for value in (perms or {}).get('process_campus') or []:
            if str(value) in known:
                rows.append(through(customuser_id=user_id, campus_id=uuid.UUID(str(value))))
    through.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0092_campus_saml_idps'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='process_campuses',
            field=models.ManyToManyField(blank=True, related_name='staff_users', to='cis.campus'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
