# Generated by Django 5.2.17 on 2026-09-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0094_process_campuses_sole_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschool',
            name='is_cte',
            field=models.BooleanField(default=False, help_text='Career & Technical Education school', verbose_name='Is CTE'),
        ),
        migrations.AddField(
            model_name='historicalhighschool',
            name='is_cte',
            field=models.BooleanField(default=False, help_text='Career & Technical Education school', verbose_name='Is CTE'),
        ),
    ]
