# Generated by Django 5.2.17 on 2026-10-02 09:45

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0095_highschool_is_cte'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchoolCampus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('building_code', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='highschool_links', to='cis.campus')),
                ('highschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_links', to='cis.highschool')),
            ],
            options={
                'verbose_name_plural': 'high school campuses',
            },
        ),
        migrations.AddField(
            model_name='highschool',
            name='campuses',
            field=models.ManyToManyField(blank=True, related_name='highschools', through='cis.HighSchoolCampus', to='cis.campus'),
        ),
        migrations.CreateModel(
            name='HistoricalHighSchoolCampus',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('building_code', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('campus', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.campus')),
                ('highschool', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cis.highschool')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical high school campus',
                'verbose_name_plural': 'historical high school campuses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='highschoolcampus',
            constraint=models.UniqueConstraint(fields=('highschool', 'campus'), name='hs_campus_once'),
        ),
        migrations.AddConstraint(
            model_name='highschoolcampus',
            constraint=models.UniqueConstraint(condition=models.Q(('building_code', ''), _negated=True), fields=('campus', 'building_code'), name='hs_campus_code_unique'),
        ),
    ]
