# Generated by Django 5.2.17 on 2026-10-06 00:58

# package-cis#64: stop keeping the password hash, SSN and last_login in user
# change history. Dropping the columns also deletes every copy already stored;
# that loss is intended and is not undone by migrating backwards (the columns
# come back empty).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0097_highschool_campus_backfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='ssn',
        ),
    ]
