# Generated by Django 5.2.17 on 2026-10-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cis', '0099_default_manage_student_recommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hsadministratorposition',
            options={'permissions': [('can_manage_student_recommendation', 'Can manage student recommendations'), ('can_verify_roster', 'Can verify class rosters'), ('can_bulk_upload_students', 'Can bulk upload students'), ('can_bulk_enroll', 'Can bulk enroll'), ('can_bulk_upload_supporting_docs', 'Can upload supporting documents'), ('can_manage_school_personnel', 'Can manage school personnel'), ('can_manage_future_sections', 'Can manage future sections'), ('can_submit_drop_requests', 'Can submit drop requests'), ('can_submit_grades', 'Can submit grades')]},
        ),
        migrations.AddField(
            model_name='hsadministratorposition',
            name='permissions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codename__in': ('can_manage_student_recommendation', 'can_verify_roster', 'can_bulk_upload_students', 'can_bulk_enroll', 'can_bulk_upload_supporting_docs', 'can_manage_school_personnel', 'can_manage_future_sections', 'can_submit_drop_requests', 'can_submit_grades'), 'content_type__app_label': 'cis', 'content_type__model': 'hsadministratorposition'}, related_name='hsadmin_positions', to='auth.permission'),
        ),
    ]
