# Generated by Django 5.2.17 on 2026-10-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0101_hsadmin_permissions_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentferpa',
            name='legacy_campus',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
